# develop stage
FROM node:lts-alpine as develop-stage

WORKDIR /app

# start app
CMD ["npm", "run", "serve"]

# install the dependencies
COPY package*.json ./
RUN npm install

# add /app/node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY . .
