# develop stage
FROM node:lts-alpine as develop-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

# add /app/node_modules/.bin to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY . .

# start app
CMD ["npm", "run", "serve"]