version: "3.7"


services: 
    # nginx service that will be running as the reverse proxy
    nginx:
        build: 
            context: .
            dockerfile: ./nginx/Dockerfile
        restart: on-failure
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
        depends_on: 
            - backend
            - frontend
        # command: nginx -g 'daemon off;'
    
    # backend service that will run django
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        hostname: backend
        ports: 
            - 8000:8000
        volumes: 
            - ./backend:/backend/project:rw
        depends_on: 
            - db
        env_file: .env
        command: >
            sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn goalMonitor.wsgi -b 0.0.0.0:8000"
    
    db:
        image: postgres:latest
        hostname: db
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
            - 5432
    
    redis:
        image: redis:latest
        hostname: redis
        ports: 
            - 6379

        
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev     # Change the Dockerfile which should be used for production and development
        ports: 
            - 8080:8080
        # volumes:
        #     - ~/.composer-docker/cache:/root/.composer/cache:delegated
        #     - ./frontend:/app:cached
        volumes: 
            - ./frontend:/app:rw               # This volumes is used in the development stage
        depends_on: 
            - backend
        restart: on-failure
        environment: 
            - CHOKIDAR_USEPOLLING=true