# Generated by Django 3.1.3 on 2020-11-26 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_auto_20201126_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuartelyGoal',
            new_name='QuarterlyGoal',
        ),
    ]
