# Generated by Django 3.1.3 on 2020-11-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20201126_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_goals', to='goals.weeklygoal'),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_goals', to='goals.quarterlygoal'),
        ),
        migrations.AlterField(
            model_name='quarterlygoal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterly_goals', to='goals.yearlygoal'),
        ),
        migrations.AlterField(
            model_name='weeklygoal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_goals', to='goals.monthlygoal'),
        ),
    ]
