# Generated by Django 3.1.3 on 2020-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20201127_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
