# Generated by Django 3.1.3 on 2020-11-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goal_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='duration',
            new_name='time_tracked',
        ),
    ]
