# Generated by Django 3.1.3 on 2020-11-27 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20201127_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='deadline',
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 20, 5, 6, 313241, tzinfo=utc), null=True),
        ),
    ]
