# Generated by Django 3.1.3 on 2020-11-27 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20201127_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 20, 8, 41, 361921, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='quarterlygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 20, 8, 41, 362874, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 20, 8, 41, 363946, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='weeklygoal',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 20, 8, 41, 359984, tzinfo=utc), null=True),
        ),
    ]
